
gateway:
  build: ./services/nginx
  ports:
    - "80:80"
  volumes:
    - ./app/dist:/usr/share/nginx/html
  links:
    - pgapi
    - server

pgapi:
  build: ./services/postgrest
  dockerfile: Dockerfile.interface
  restart: always
  links:
    - db

db:
  build: ./services/postgrest
  dockerfile: Dockerfile.db
  environment:
    - "POSTGRES_USER=admin"
    - "POSTGRES_PASS=alpine"
    - "POSTGRES_DB=projects"
  volumes:
    - data:/var/lib/postgresql/data
  ports:
    - "5432:5432"

server:
  build: ./server

static:
  build: ./app
  volumes:
    - statics:/src/dist
